[metadata]
description-file = README.md

[aliases]
test=pytest

[flake8]
max-line-length=120
exclude = .git, .nox, .venv, build, dist
# black compatibility
extend-ignore = E203
# ignore import unused in __init__
per-file-ignores = __init__.py:F401

[isort]
# black compatible config
# https://black.readthedocs.io/en/stable/compatible_configs.html
multi_line_output = 3
include_trailing_comma = True
force_grid_wrap = 0
use_parentheses = True
ensure_newline_before_comments = True
line_length = 120

[coverage:run]
# measure branch coverage in addition to statement coverage
branch = True
# restrict coverage on neogit package only
source = neogit

# mandatory section, despite what the docs says
[mypy]

[mypy-neo4j.*]
ignore_missing_imports = True

[mypy-py2neo.ogm.*]
ignore_missing_imports = True

[mypy-docopt.*]
ignore_missing_imports = True

[mypy-dynaconf.*]
ignore_missing_imports = True

[mypy-coloredlogs.*]
ignore_missing_imports = True

[tool:pytest]
markers =
    dev: mark a test as only for development with IPDB purposes
