name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        make_target: [fmt, lint, type, vermin]
        include:
          # black needs --check to return an error code
          - make_target: fmt
            extra_args: --check
    steps:
      - uses: actions/checkout@v4

      - name: Project setup
        uses: ./.github/actions/common-setup

      - name: run make target
        run: poetry run poe ${{ matrix.make_target }} ${{ matrix.extra_args }}

  unit_test:
    strategy:
      matrix:
        # TODO: add windows-latest and ditch Makefile
        os: [ubuntu-latest]
        python_version: ['3.11']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Project setup
        uses: ./.github/actions/common-setup
        with:
          python_version: "${{ matrix.python_version }}"

      - name: Check format
        run: poetry run poe unit_test

  integration_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neo4j: ['4.2.4']
        python: ['3.11']
    services:
      minio:
        image: minio/minio:RELEASE.2024-12-05T15-54-02Z
        ports:
          - 9000:9000
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
      neo4j:
        image: neo4j:${{ matrix.neo4j }}
        ports:
          - 7687:7687
          # also expose the HTTP port since we use this to test whether the DB is ready
          - 7474:7474
        env:
          NEO4J_AUTH: none
    steps:
      - uses: actions/checkout@v4

      - name: Project setup
        uses: ./.github/actions/common-setup
        with:
          python_version: ${{ matrix.python }}

      # pass --externdb to use github actions service containers instead
      # poetry run doesn't play well with our Makefile EXTRA_ARGS hack
      - name: Run integration tests
        run: |
          source $(poetry env info --path)/bin/activate
          poe integration_test -- --externdb
        env:
          NEOGIT_OBJECT__PROVIDER: minio
          NEOGIT_OBJECT__HOST: 127.0.0.1
          NEOGIT_OBJECT__PORT: 9000
          NEOGIT_OBJECT__KEY: minioadmin
          NEOGIT_OBJECT__SECRET: minioadmin
          NEOGIT_OBJECT__SECURE: false

  build_image:
    # build Docker image, but don't push it
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.11']
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          build-args: |
            python_version=${{ matrix.python_version}}
          tags: wenzel/neogit:latest

  release:
    needs: [dev, unit_test, integration_test, build_image]
    # if push on master and tag starts with 'v*'
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create a Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          body_path: ${{ github.workspace }}/.github/RELEASE.md
