name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        make_target: [fmt, lint, type, vermin]
        include:
          # black needs --check to return an error code
          - make_target: fmt
            extra_args: --check
    steps:
      - uses: actions/checkout@v3

      - name: Project setup
        uses: ./.github/actions/common-setup

      - name: Check format
        run: poetry run make ${{ matrix.make_target }} -- ${{ matrix.extra_args }}

  test:
    strategy:
      matrix:
        # TODO: add windows-latest and ditch Makefile
        os: [ubuntu-latest]
        python_version: ['3.8', '3.9', '3.10', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Project setup
        uses: ./.github/actions/common-setup
        with:
          python_version: "${{ matrix.python_version }}"

      - name: Check format
        run: poetry run make unit_test

  integration_test:
    runs-on: ubuntu-latest
    services:
      minio:
        # need to use a custom image because Github Actions doesn't allow us to pass a CMD
        # and the official Minio image needs a "server" command
        image: lazybit/minio
        ports:
          - 9000:9000
      neo4j:
        image: neo4j:4.2.4
        ports:
          - 7687:7687
          # also expose the HTTP port since we use this to test whether the DB is ready
          - 7474:7474
        env:
          NEO4J_AUTH: none
    steps:
      - uses: actions/checkout@v2

      - name: Project setup
        uses: ./.github/actions/common-setup

      # pass --externdb to use github actions service containers instead
      - name: Run integration tests
        run: poetry run make integration_test -- --externdb
        env:
          NEOGIT_OBJECT__PROVIDER: minio
          NEOGIT_OBJECT__HOST: 127.0.0.1
          NEOGIT_OBJECT__PORT: 9000
          NEOGIT_OBJECT__KEY: minioadmin
          NEOGIT_OBJECT__SECRET: minioadmin
          NEOGIT_OBJECT__SECURE: false

  build_image:
    # build Docker image, but don't push it
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          push: false
          tags: wenzel/neogit:latest

  release:
    needs: [dev, test, build_image]
    # if push on master and tag starts with 'v*'
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create a Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          body_path: ${{ github.workspace }}/.github/RELEASE.md
